### Demander un lien de réinitialisation (optionnel)
POST http://localhost:8000/api/auth/password-reset/
Content-Type: application/json

{
  "email": "magloireaffokpe6@gmail.com"
}

### Confirmer la réinitialisation avec le token reçu
### Confirmer la réinitialisation avec le token exact

### Confirmer la réinitialisation avec le token reçu (sans coupure)
POST http://localhost:8000/api/auth/password-reset-confirm/
Content-Type: application/json

{
  "token": "5OCcgWI8SBLRmg0wbo3AbrD7fpCD2pVC4CyRqdEhLZB2WEoG9eidXsaUPODYklMx",
  "new_password": "Magloire@67",
  "new_password_confirm": "Magloire@67"
}