# Generated by Django 6.0.4 on 2026-04-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, verbose_name='adresse de livraison')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_TRANSIT', 'En transit'), ('DELIVERED', 'Livrée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20, verbose_name='statut de livraison')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='date de livraison prévue')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'livraison',
                'verbose_name_plural': 'livraisons',
            },
        ),
    ]
