# Generated by Django 6.0.4 on 2026-04-14 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('FRUITS', 'Fruits'), ('VEGETABLES', 'Légumes'), ('CEREALS', 'Céréales'), ('MEAT', 'Viande'), ('DAIRY', 'Produits laitiers'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix (FCFA)')),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='quantité disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='agriculteur')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'), models.Index(fields=['farmer'], name='products_pr_farmer__a9075c_idx'), models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx')],
            },
        ),
    ]
